#!/bin/bash

# for ip in $(cat ./allowed_address_pairs)
#   do
#	echo $ip
#   done	

array=()
  getArray() {
	i=0
	while read line
  do
		array[i]=$line
		i=$(($i +1))
	done
   }

	getArray "allowed_address_pairs"
